/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The notification text shown in the toast. Bind this to the message column of your data-backend table. Each newly published value triggers one toast. Empty values are ignored and line breaks are preserved.
 */
export type Message = string;
/**
 * The severity of the toast, controlling its accent color and icon. Bind this to a column producing one of: success, error, info, warning. Defaults to 'info' when missing or unrecognized.
 */
export type Severity = "success" | "error" | "info" | "warning";
/**
 * How long each toast stays visible before auto-dismissing, in milliseconds. Set to 0 to keep toasts until they are manually closed (the close button is forced on in that case). Defaults to 4000.
 */
export type DisplayTimeMs = number;
/**
 * Where the toast stack is anchored inside the widget tile. Defaults to 'top-right'.
 */
export type Position = "top-right" | "top-left" | "top-center" | "bottom-right" | "bottom-left" | "bottom-center";
/**
 * Maximum number of toasts shown at once. When exceeded, the oldest toast is dismissed to make room. Defaults to 3.
 */
export type MaxVisible = number;
/**
 * Show the severity icon (check / cross / info / warning) on the left of each toast. Defaults to true.
 */
export type ShowIcon = boolean;
/**
 * Show a close (x) button on each toast so it can be dismissed manually. Always shown when Display Time is 0. Defaults to true.
 */
export type ShowCloseButton = boolean;

/**
 * A transient toast / notification widget. The backend publishes rows into a data-backend table; bind the message and severity columns of that table to this widget, and each newly published row pops up a short-lived toast inside the widget tile. Use it to surface live success / error / info / warning events on a dashboard. The message text and severity are data-driven (they reflect the latest published row), while the display time, position within the tile, stacking limit and styling are static configuration.
 */
export interface InputData {
    message?: Message;
    type?: Severity;
    displayTime?: DisplayTimeMs;
    position?: Position;
    maxVisible?: MaxVisible;
    showIcon?: ShowIcon;
    showCloseButton?: ShowCloseButton;
    successColor?: SuccessColor;
    errorColor?: ErrorColor;
    infoColor?: InfoColor;
    warningColor?: WarningColor;
    [k: string]: unknown;
}
/**
 * Optional override for the accent color of success toasts (e.g. '#2e7d32'). If empty, a built-in green is used.
 */
export interface SuccessColor {
    [k: string]: unknown;
}
/**
 * Optional override for the accent color of error toasts (e.g. '#c62828'). If empty, a built-in red is used.
 */
export interface ErrorColor {
    [k: string]: unknown;
}
/**
 * Optional override for the accent color of info toasts (e.g. '#1565c0'). If empty, a built-in blue is used.
 */
export interface InfoColor {
    [k: string]: unknown;
}
/**
 * Optional override for the accent color of warning toasts (e.g. '#ed6c02'). If empty, a built-in amber is used.
 */
export interface WarningColor {
    [k: string]: unknown;
}
